# Importando as bibliotecas

In [1]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
import optuna
import mlflow

import warnings
warnings.filterwarnings("ignore")

c:\Users\felip\miniconda3\envs\mlops\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Carregando a base de dados

In [2]:
data = pd.read_csv('data/bike.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  cnt         17379 non-null  int64
dtypes: float64(4), int64(10), object(1)
memory usage: 2.0+ MB

In [3]:
data.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
3,4,1/1/2011,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
4,5,1/1/2011,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

# Preparando o Dataset - Treino e Teste

In [4]:
# Converte a coluna 'dteday' para o tipo datetime
data['dteday'] = pd.to_datetime(data['dteday'])

In [5]:
# Divisão 80% treino e 20% teste
train = data.loc[data['dteday']< '2012-08-10']
test = data.loc[data['dteday']>= '2012-08-10']

In [6]:
# Porcentagem dos dados de treino
round(train.shape[0] / data.shape[0], 2)

0.8

In [7]:
train.drop(['instant', 'dteday'], axis=1, inplace=True)
test.drop(['instant', 'dteday'], axis=1, inplace=True)

# Validação Cruzada p/ teste de Modelos

In [8]:
# Separando as features e o target de treino
features_train = train.drop('cnt', axis=1)
target_train = train['cnt']

# Separando as features e o target de teste
features_test = test.drop('cnt', axis=1)
target_test = test['cnt']

In [9]:
def cross_validate_rmse(model, X, y, cv=5):
    scores = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv)
    rmse_scores = -scores
    mean_rmse = rmse_scores.mean()
    std_rmse = rmse_scores.std()
    return rmse_scores, mean_rmse, std_rmse

# Decision Tree
rmse_scores, mean_rmse, std_rmse = cross_validate_rmse(DecisionTreeRegressor(random_state=42), features_train, target_train)
print(f'Decision Tree: RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

# Random Forest
rmse_scores, mean_rmse, std_rmse = cross_validate_rmse(RandomForestRegressor(n_estimators=1000, random_state=42, n_jobs=-1), features_train, target_train)
print(f'Random Forest: RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

# XGBoost with DataFrame
rmse_scores, mean_rmse, std_rmse = cross_validate_rmse(xgb.XGBRegressor(objective='reg:squarederror', eval_metric='rmse', seed=42), features_train, target_train)
print(f'XGBoost (DataFrame): RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

# XGBoost with Dmatrix
dtrain = xgb.DMatrix(features_train, label=target_train)
params = {
    'objective': 'reg:squarederror',
    'eval_metric': 'rmse',
    'seed': 42
}
cv_results = xgb.cv(params, dtrain, num_boost_round=1000, nfold=5, early_stopping_rounds=10)
mean_rmse = cv_results['test-rmse-mean'].min()
std_rmse = cv_results['test-rmse-std'].min()
print(f'XGBoost (DMatrix): RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

Decision Tree: RMSE médio: 90.62, Desvio padrão: 15.20
Random Forest: RMSE médio: 71.25, Desvio padrão: 14.70
XGBoost (DataFrame): RMSE médio: 62.06, Desvio padrão: 7.56
XGBoost (DMatrix): RMSE médio: 36.87, Desvio padrão: 1.39

# Experiment Tracking com MLflow e XGBoost

In [10]:
# Instancia o MLflow
mlflow.set_experiment("bike_rental")
mlflow.set_tracking_uri("http://localhost:5000")

2025/02/20 16:57:27 INFO mlflow.tracking.fluent: Experiment with name 'bike_rental' does not exist. Creating a new experiment.

In [20]:
# Otimização de hiperparâmetros com Optuna e registro no MLflow

def objective(trial):
    # Define os hiperparâmetros a serem otimizados
    param = {
        'objective': 'reg:squarederror',
        'eval_metric': 'rmse',
        'seed': 42,
        'max_depth': trial.suggest_int("max_depth", 3, 10),
        'learning_rate': trial.suggest_float("learning_rate", 0.01, 0.3),
        'gamma': trial.suggest_float("gamma", 0.0, 5.0),
        'min_child_weight': trial.suggest_int("min_child_weight", 1, 10),
        'subsample': trial.suggest_float("subsample", 0.5, 1.0),
        'colsample_bytree': trial.suggest_float("colsample_bytree", 0.5, 1.0)
    }
    
    # Inicia um run MLflow aninhado para registrar a trial corrente
    with mlflow.start_run(nested=True):

        # Registra os hiperparâmetros no MLflow
        mlflow.log_params(param)
        
        # Executa a validação cruzada com xgb.cv usando dtrain (definido em célula anterior)
        cv_results = xgb.cv(
            params=param,
            dtrain=dtrain,
            num_boost_round=1000,
            nfold=5,
            early_stopping_rounds=10,
            verbose_eval=False
        )
        
        # Retorna o menor RMSE obtido na validação cruzada
        best_rmse = cv_results['test-rmse-mean'].min()
        mlflow.log_metric("best_rmse", best_rmse)
    
    return best_rmse

# Cria um estudo Optuna e otimiza a função objetivo
study_dmatrix = optuna.create_study(direction="minimize")
study_dmatrix.optimize(objective, n_trials=50)

print("Melhor resultado:")
print(study_dmatrix.best_trial)

[I 2025-02-20 17:12:22,418] A new study created in memory with name: no-name-2c5d48ad-083e-48f0-a7e8-71543af10c86
[I 2025-02-20 17:12:24,301] Trial 0 finished with value: 40.44427104517274 and parameters: {'max_depth': 9, 'learning_rate': 0.2984116907046961, 'gamma': 1.9987419929143484, 'min_child_weight': 2, 'subsample': 0.7876169835103024, 'colsample_bytree': 0.6314287014771984}. Best is trial 0 with value: 40.44427104517274.

🏃 View run unruly-sponge-266 at: http://localhost:5000/#/experiments/788856940458785600/runs/26e68c5748a743b7baafd4f129008839
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:28,182] Trial 1 finished with value: 35.40673301808342 and parameters: {'max_depth': 6, 'learning_rate': 0.09479337929984202, 'gamma': 3.148563880230442, 'min_child_weight': 5, 'subsample': 0.8997890036581935, 'colsample_bytree': 0.8955866274115096}. Best is trial 1 with value: 35.40673301808342.

🏃 View run nebulous-crane-519 at: http://localhost:5000/#/experiments/788856940458785600/runs/f446741f95cc4a4788ec9b3ac1b7781e
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:34,682] Trial 2 finished with value: 35.606441214204224 and parameters: {'max_depth': 8, 'learning_rate': 0.05494035356415756, 'gamma': 1.2404745667271233, 'min_child_weight': 2, 'subsample': 0.9409221310587981, 'colsample_bytree': 0.5435838728760454}. Best is trial 1 with value: 35.40673301808342.

🏃 View run entertaining-fox-896 at: http://localhost:5000/#/experiments/788856940458785600/runs/70f80f2916564b90b64efef9c62a17bf
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:37,648] Trial 3 finished with value: 35.366504348779344 and parameters: {'max_depth': 9, 'learning_rate': 0.10906739638661445, 'gamma': 4.4426618787076855, 'min_child_weight': 7, 'subsample': 0.7903744119662812, 'colsample_bytree': 0.8625763021569006}. Best is trial 3 with value: 35.366504348779344.

🏃 View run caring-bee-963 at: http://localhost:5000/#/experiments/788856940458785600/runs/8629f98ee726403499f7c6bdf197be1d
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:45,955] Trial 4 finished with value: 38.788989312920556 and parameters: {'max_depth': 4, 'learning_rate': 0.08324435079152538, 'gamma': 3.0948150768566163, 'min_child_weight': 6, 'subsample': 0.5848058589896553, 'colsample_bytree': 0.6456495801107522}. Best is trial 3 with value: 35.366504348779344.

🏃 View run fearless-whale-461 at: http://localhost:5000/#/experiments/788856940458785600/runs/d17da61dd2ec40cd8bd64bf2e71685b4
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:48,669] Trial 5 finished with value: 37.94701178098946 and parameters: {'max_depth': 6, 'learning_rate': 0.24838803461070252, 'gamma': 3.521474177151023, 'min_child_weight': 8, 'subsample': 0.7816233900550891, 'colsample_bytree': 0.6852417880041475}. Best is trial 3 with value: 35.366504348779344.

🏃 View run wistful-bird-466 at: http://localhost:5000/#/experiments/788856940458785600/runs/79369e1b9aaf43c58c2b3eaab76f84a0
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:55,626] Trial 6 finished with value: 41.96734912323957 and parameters: {'max_depth': 3, 'learning_rate': 0.1970555886485551, 'gamma': 0.897366782224186, 'min_child_weight': 8, 'subsample': 0.9558124772533498, 'colsample_bytree': 0.9419564613607134}. Best is trial 3 with value: 35.366504348779344.

🏃 View run efficient-horse-380 at: http://localhost:5000/#/experiments/788856940458785600/runs/cb2d145c7f4846bf881f99e64ae4ae04
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:57,626] Trial 7 finished with value: 36.76122246859107 and parameters: {'max_depth': 7, 'learning_rate': 0.21617280702052896, 'gamma': 1.3867511142554974, 'min_child_weight': 6, 'subsample': 0.6957502887589411, 'colsample_bytree': 0.8388849166632547}. Best is trial 3 with value: 35.366504348779344.

🏃 View run unique-colt-544 at: http://localhost:5000/#/experiments/788856940458785600/runs/33ce4ab34120436992c4208b0f1ca019
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:12:58,865] Trial 8 finished with value: 42.65885305083329 and parameters: {'max_depth': 10, 'learning_rate': 0.2888408163042987, 'gamma': 4.06633447369801, 'min_child_weight': 5, 'subsample': 0.5591454489043679, 'colsample_bytree': 0.6396113126984594}. Best is trial 3 with value: 35.366504348779344.

🏃 View run bold-auk-669 at: http://localhost:5000/#/experiments/788856940458785600/runs/66f66a3e51714848ac5118f160f1381f
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:13:02,415] Trial 9 finished with value: 38.32038708582719 and parameters: {'max_depth': 10, 'learning_rate': 0.12683419679299945, 'gamma': 1.6300357639496492, 'min_child_weight': 2, 'subsample': 0.5038278918375227, 'colsample_bytree': 0.6683845918697068}. Best is trial 3 with value: 35.366504348779344.

🏃 View run tasteful-crab-351 at: http://localhost:5000/#/experiments/788856940458785600/runs/d593cb3518f64cb99823cc410a8532fa
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:13:16,001] Trial 10 finished with value: 34.52827377923885 and parameters: {'max_depth': 8, 'learning_rate': 0.025034348287395536, 'gamma': 4.827547541736299, 'min_child_weight': 10, 'subsample': 0.6897631655908519, 'colsample_bytree': 0.8057821979258264}. Best is trial 10 with value: 34.52827377923885.

🏃 View run enchanting-stoat-685 at: http://localhost:5000/#/experiments/788856940458785600/runs/615fdecabd734347a6de62da771526ba
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:13:29,267] Trial 11 finished with value: 35.34046975468591 and parameters: {'max_depth': 8, 'learning_rate': 0.010583724047541484, 'gamma': 4.846918822197603, 'min_child_weight': 10, 'subsample': 0.6815814636636928, 'colsample_bytree': 0.7728344382524079}. Best is trial 10 with value: 34.52827377923885.

🏃 View run redolent-whale-178 at: http://localhost:5000/#/experiments/788856940458785600/runs/e8786c4f243b45b083ccedbdc18b3ba6
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:13:40,840] Trial 12 finished with value: 35.18540758442095 and parameters: {'max_depth': 7, 'learning_rate': 0.018144243806648825, 'gamma': 4.940983481594773, 'min_child_weight': 10, 'subsample': 0.6743979666562869, 'colsample_bytree': 0.7783904413649678}. Best is trial 10 with value: 34.52827377923885.

🏃 View run brawny-moth-193 at: http://localhost:5000/#/experiments/788856940458785600/runs/156991023c3d4d0a8ebceeaa261d9fac
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:13:49,857] Trial 13 finished with value: 41.238152851068435 and parameters: {'max_depth': 5, 'learning_rate': 0.010986829147332868, 'gamma': 0.09626776878532883, 'min_child_weight': 10, 'subsample': 0.649899861365886, 'colsample_bytree': 0.7687580846485471}. Best is trial 10 with value: 34.52827377923885.

🏃 View run mercurial-mule-122 at: http://localhost:5000/#/experiments/788856940458785600/runs/1b4df23bda5142379c1fe7bca4f15cb9
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:13:57,030] Trial 14 finished with value: 34.81372272380858 and parameters: {'max_depth': 7, 'learning_rate': 0.05267740873728549, 'gamma': 4.96892779357485, 'min_child_weight': 9, 'subsample': 0.6238011977185011, 'colsample_bytree': 0.974394350880853}. Best is trial 10 with value: 34.52827377923885.

🏃 View run zealous-mare-381 at: http://localhost:5000/#/experiments/788856940458785600/runs/8ea3579cf9104f9892de86eb219e311b
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:02,201] Trial 15 finished with value: 34.72515701758845 and parameters: {'max_depth': 8, 'learning_rate': 0.05615780858758476, 'gamma': 3.859008097841772, 'min_child_weight': 9, 'subsample': 0.8505900519252076, 'colsample_bytree': 0.9428457963168417}. Best is trial 10 with value: 34.52827377923885.

🏃 View run languid-robin-595 at: http://localhost:5000/#/experiments/788856940458785600/runs/17dd80adaea849e6b21d1dbcc00ef8c5
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:04,458] Trial 16 finished with value: 35.563679593874994 and parameters: {'max_depth': 8, 'learning_rate': 0.14080509759515186, 'gamma': 3.7505306467290405, 'min_child_weight': 8, 'subsample': 0.8430201131340713, 'colsample_bytree': 0.9255892947542103}. Best is trial 10 with value: 34.52827377923885.

🏃 View run welcoming-wolf-995 at: http://localhost:5000/#/experiments/788856940458785600/runs/ed9e1f7f72a94edabd97d07dff96a7db
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:09,522] Trial 17 finished with value: 34.7622606166331 and parameters: {'max_depth': 9, 'learning_rate': 0.05776970313685009, 'gamma': 2.6715097619560453, 'min_child_weight': 9, 'subsample': 0.7332452123704158, 'colsample_bytree': 0.85638036019578}. Best is trial 10 with value: 34.52827377923885.

🏃 View run magnificent-crow-886 at: http://localhost:5000/#/experiments/788856940458785600/runs/16a8880e273b4508bace4e19149f76b8
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:18,802] Trial 18 finished with value: 36.09650227948238 and parameters: {'max_depth': 5, 'learning_rate': 0.04590244586818247, 'gamma': 4.154382811070379, 'min_child_weight': 4, 'subsample': 0.8585361522509136, 'colsample_bytree': 0.9817902093246127}. Best is trial 10 with value: 34.52827377923885.

🏃 View run defiant-rat-763 at: http://localhost:5000/#/experiments/788856940458785600/runs/100eac5111e04258a16cd43f879b1b10
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:21,382] Trial 19 finished with value: 36.660784048404 and parameters: {'max_depth': 8, 'learning_rate': 0.1738198794172344, 'gamma': 4.365421704426531, 'min_child_weight': 9, 'subsample': 0.8747126747444595, 'colsample_bytree': 0.7216408261406267}. Best is trial 10 with value: 34.52827377923885.

🏃 View run debonair-kit-25 at: http://localhost:5000/#/experiments/788856940458785600/runs/bf746a2deafc45f786d6b7dfe4a7ea99
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:24,900] Trial 20 finished with value: 35.14277376178846 and parameters: {'max_depth': 9, 'learning_rate': 0.07782976227354306, 'gamma': 2.450302646834448, 'min_child_weight': 7, 'subsample': 0.7356604635504086, 'colsample_bytree': 0.8159862267472755}. Best is trial 10 with value: 34.52827377923885.

🏃 View run rebellious-fish-800 at: http://localhost:5000/#/experiments/788856940458785600/runs/4ad5e3e574374e04ac8fc834abb05828
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:32,232] Trial 21 finished with value: 34.40783537527264 and parameters: {'max_depth': 9, 'learning_rate': 0.04032633610146599, 'gamma': 3.103460583323776, 'min_child_weight': 9, 'subsample': 0.732925837962594, 'colsample_bytree': 0.8765889068068179}. Best is trial 21 with value: 34.40783537527264.

🏃 View run unleashed-foal-742 at: http://localhost:5000/#/experiments/788856940458785600/runs/094db0f5a7864ee7be3235e22ee332e4
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:40,501] Trial 22 finished with value: 34.97183400028729 and parameters: {'max_depth': 10, 'learning_rate': 0.03635580778498905, 'gamma': 3.548037103741821, 'min_child_weight': 9, 'subsample': 0.9940036100172667, 'colsample_bytree': 0.8954186667541003}. Best is trial 21 with value: 34.40783537527264.

🏃 View run bemused-mouse-412 at: http://localhost:5000/#/experiments/788856940458785600/runs/29c1b923df044ac08cd5ca96607de186
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:44,598] Trial 23 finished with value: 35.01486877703091 and parameters: {'max_depth': 8, 'learning_rate': 0.07277137914733509, 'gamma': 3.0578387034027545, 'min_child_weight': 10, 'subsample': 0.8187807150691299, 'colsample_bytree': 0.8115209161210191}. Best is trial 21 with value: 34.40783537527264.

🏃 View run invincible-cub-27 at: http://localhost:5000/#/experiments/788856940458785600/runs/61d09bc7a27f4480ba04a6d5c26193d7
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:47,948] Trial 24 finished with value: 35.05641037889011 and parameters: {'max_depth': 9, 'learning_rate': 0.10674860561015771, 'gamma': 3.8575639896957643, 'min_child_weight': 7, 'subsample': 0.7384952763711831, 'colsample_bytree': 0.9049910891807265}. Best is trial 21 with value: 34.40783537527264.

🏃 View run agreeable-bear-703 at: http://localhost:5000/#/experiments/788856940458785600/runs/92ef2bc8c7144ea88ff137c72c1cc2ba
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:14:57,634] Trial 25 finished with value: 34.487573848821505 and parameters: {'max_depth': 7, 'learning_rate': 0.03323913771408851, 'gamma': 4.61003998396001, 'min_child_weight': 8, 'subsample': 0.7060105872453146, 'colsample_bytree': 0.9456295112288637}. Best is trial 21 with value: 34.40783537527264.

🏃 View run silent-asp-361 at: http://localhost:5000/#/experiments/788856940458785600/runs/8e11993e3fe64cf2a51c103ceb05c0bf
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:07,766] Trial 26 finished with value: 35.75265219585446 and parameters: {'max_depth': 6, 'learning_rate': 0.019890332702058516, 'gamma': 4.542939397421446, 'min_child_weight': 8, 'subsample': 0.625213053846692, 'colsample_bytree': 0.9988990651010943}. Best is trial 21 with value: 34.40783537527264.

🏃 View run upset-snipe-996 at: http://localhost:5000/#/experiments/788856940458785600/runs/f288c153ebec43ee8dff58eb78f55927
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:18,837] Trial 27 finished with value: 34.89321584559984 and parameters: {'max_depth': 7, 'learning_rate': 0.02933724923355472, 'gamma': 4.625100274761877, 'min_child_weight': 10, 'subsample': 0.7085248350597753, 'colsample_bytree': 0.7172097325640345}. Best is trial 21 with value: 34.40783537527264.

🏃 View run learned-bass-75 at: http://localhost:5000/#/experiments/788856940458785600/runs/82810431d0bd49089180a7c36165f2a7
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:22,749] Trial 28 finished with value: 36.383783694028466 and parameters: {'max_depth': 5, 'learning_rate': 0.16305927585336707, 'gamma': 2.5538189647234, 'min_child_weight': 4, 'subsample': 0.7633731828718815, 'colsample_bytree': 0.8721518901722641}. Best is trial 21 with value: 34.40783537527264.

🏃 View run big-hog-759 at: http://localhost:5000/#/experiments/788856940458785600/runs/654c5ed3a8cb435a88973a05b15eb0ef
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:26,282] Trial 29 finished with value: 37.31324324569409 and parameters: {'max_depth': 10, 'learning_rate': 0.12483058134962449, 'gamma': 2.024141819191555, 'min_child_weight': 7, 'subsample': 0.8089231631639832, 'colsample_bytree': 0.5467841883816338}. Best is trial 21 with value: 34.40783537527264.

🏃 View run fortunate-snail-205 at: http://localhost:5000/#/experiments/788856940458785600/runs/65e93d757a9a41f1adac4f22f55a44f5
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:33,832] Trial 30 finished with value: 34.90677992176516 and parameters: {'max_depth': 7, 'learning_rate': 0.03591259898722338, 'gamma': 3.376846911776994, 'min_child_weight': 1, 'subsample': 0.5906762898735836, 'colsample_bytree': 0.8153470121796704}. Best is trial 21 with value: 34.40783537527264.

🏃 View run industrious-swan-260 at: http://localhost:5000/#/experiments/788856940458785600/runs/a16e9ce8dbca4634b0b1dfb51a1e8eea
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:38,367] Trial 31 finished with value: 34.85530633139589 and parameters: {'max_depth': 8, 'learning_rate': 0.0680264971299362, 'gamma': 4.067499456895326, 'min_child_weight': 9, 'subsample': 0.6616953053072104, 'colsample_bytree': 0.947652287940111}. Best is trial 21 with value: 34.40783537527264.

🏃 View run caring-panda-295 at: http://localhost:5000/#/experiments/788856940458785600/runs/af116042630a4e3b9ef7ec14da57ec7a
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:41,668] Trial 32 finished with value: 35.038030792594284 and parameters: {'max_depth': 9, 'learning_rate': 0.09121837450884625, 'gamma': 3.8153385473999086, 'min_child_weight': 9, 'subsample': 0.7098161513892002, 'colsample_bytree': 0.9538357135210328}. Best is trial 21 with value: 34.40783537527264.

🏃 View run receptive-hen-955 at: http://localhost:5000/#/experiments/788856940458785600/runs/3774162161d34e5fa617f57ea3150d66
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:49,486] Trial 33 finished with value: 34.54531051592952 and parameters: {'max_depth': 9, 'learning_rate': 0.04073431825512544, 'gamma': 4.215658110536302, 'min_child_weight': 8, 'subsample': 0.9027684621895995, 'colsample_bytree': 0.9028120004817047}. Best is trial 21 with value: 34.40783537527264.

🏃 View run loud-fawn-977 at: http://localhost:5000/#/experiments/788856940458785600/runs/2b7a93942b604662a1812431c63c3c93
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:15:58,751] Trial 34 finished with value: 34.527831846650784 and parameters: {'max_depth': 9, 'learning_rate': 0.032763166934961264, 'gamma': 4.621662162435321, 'min_child_weight': 8, 'subsample': 0.8921579186272461, 'colsample_bytree': 0.9055742453048388}. Best is trial 21 with value: 34.40783537527264.

🏃 View run gentle-shrimp-399 at: http://localhost:5000/#/experiments/788856940458785600/runs/96f42c3920bb4987a30f2a0ae8618a91
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:01,735] Trial 35 finished with value: 35.131202316562806 and parameters: {'max_depth': 9, 'learning_rate': 0.10233751180158199, 'gamma': 4.645211605288833, 'min_child_weight': 8, 'subsample': 0.7690665403499616, 'colsample_bytree': 0.8846037578133312}. Best is trial 21 with value: 34.40783537527264.

🏃 View run powerful-ray-581 at: http://localhost:5000/#/experiments/788856940458785600/runs/3eb5e5bb7c1741bd8d854a51a93000c9
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:07,167] Trial 36 finished with value: 35.55223851396969 and parameters: {'max_depth': 6, 'learning_rate': 0.06527433665377472, 'gamma': 4.712745991929427, 'min_child_weight': 6, 'subsample': 0.6358164075799888, 'colsample_bytree': 0.8607620958018469}. Best is trial 21 with value: 34.40783537527264.

🏃 View run zealous-cod-624 at: http://localhost:5000/#/experiments/788856940458785600/runs/d8519c3dd3974c5cad088e030ae0e36d
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:19,902] Trial 37 finished with value: 35.17453678904119 and parameters: {'max_depth': 8, 'learning_rate': 0.028109098903148166, 'gamma': 4.392094971932752, 'min_child_weight': 7, 'subsample': 0.9112287030268973, 'colsample_bytree': 0.579572544327818}. Best is trial 21 with value: 34.40783537527264.

🏃 View run fortunate-bug-971 at: http://localhost:5000/#/experiments/788856940458785600/runs/60bfde745e4e4a3095a826604f02996e
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:23,585] Trial 38 finished with value: 35.1294979979388 and parameters: {'max_depth': 10, 'learning_rate': 0.09220944869805293, 'gamma': 2.793723238676108, 'min_child_weight': 10, 'subsample': 0.7245897587328459, 'colsample_bytree': 0.9235741622353034}. Best is trial 21 with value: 34.40783537527264.

🏃 View run entertaining-ape-352 at: http://localhost:5000/#/experiments/788856940458785600/runs/0f0908e1ceaf489b8dc77e8c1f8b7af6
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:31,399] Trial 39 finished with value: 34.55868132283301 and parameters: {'max_depth': 7, 'learning_rate': 0.04708430723970028, 'gamma': 2.2142857785294616, 'min_child_weight': 5, 'subsample': 0.7977298720618072, 'colsample_bytree': 0.8339668714410632}. Best is trial 21 with value: 34.40783537527264.

🏃 View run amazing-cod-604 at: http://localhost:5000/#/experiments/788856940458785600/runs/582772f49916469fb7878d11a4337747
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:33,803] Trial 40 finished with value: 36.854723815380034 and parameters: {'max_depth': 6, 'learning_rate': 0.22351369119197395, 'gamma': 3.3036069830081285, 'min_child_weight': 8, 'subsample': 0.9461061224881977, 'colsample_bytree': 0.7947427437471424}. Best is trial 21 with value: 34.40783537527264.

🏃 View run aged-doe-208 at: http://localhost:5000/#/experiments/788856940458785600/runs/5f3c9b213f40431eb1010e5b92b8a47c
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:42,117] Trial 41 finished with value: 34.6571883219673 and parameters: {'max_depth': 9, 'learning_rate': 0.03596178336815191, 'gamma': 4.239310716665305, 'min_child_weight': 8, 'subsample': 0.9088258868070128, 'colsample_bytree': 0.9124639844648029}. Best is trial 21 with value: 34.40783537527264.

🏃 View run calm-eel-52 at: http://localhost:5000/#/experiments/788856940458785600/runs/eea189d0373b46159f1e1bafcf151e0d
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:48,617] Trial 42 finished with value: 35.04808246027419 and parameters: {'max_depth': 9, 'learning_rate': 0.04663770361872324, 'gamma': 4.534123967750146, 'min_child_weight': 7, 'subsample': 0.9956131623447513, 'colsample_bytree': 0.8471367744044944}. Best is trial 21 with value: 34.40783537527264.

🏃 View run unleashed-colt-299 at: http://localhost:5000/#/experiments/788856940458785600/runs/76b909746f344e52b1ed78f17859b811
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:16:58,309] Trial 43 finished with value: 34.54233886229707 and parameters: {'max_depth': 9, 'learning_rate': 0.03076796251136104, 'gamma': 4.80336391055186, 'min_child_weight': 8, 'subsample': 0.8775456111919939, 'colsample_bytree': 0.8823016942625618}. Best is trial 21 with value: 34.40783537527264.

🏃 View run peaceful-stork-645 at: http://localhost:5000/#/experiments/788856940458785600/runs/9ac596f0dec041478b13734d442665f2
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:17:10,366] Trial 44 finished with value: 34.4402067715727 and parameters: {'max_depth': 8, 'learning_rate': 0.024587700326243973, 'gamma': 4.778474581887436, 'min_child_weight': 6, 'subsample': 0.8249834467663674, 'colsample_bytree': 0.8857002637820783}. Best is trial 21 with value: 34.40783537527264.

🏃 View run masked-boar-585 at: http://localhost:5000/#/experiments/788856940458785600/runs/d79f9a2c10d54b28999621200747a673
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:17:24,815] Trial 45 finished with value: 34.89865164648851 and parameters: {'max_depth': 8, 'learning_rate': 0.0118367007871285, 'gamma': 4.927995431455774, 'min_child_weight': 6, 'subsample': 0.7628960273043277, 'colsample_bytree': 0.8333345628107229}. Best is trial 21 with value: 34.40783537527264.

🏃 View run merciful-ram-106 at: http://localhost:5000/#/experiments/788856940458785600/runs/f2187b26bbab4efcb1a3db52d591302f
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:17:36,848] Trial 46 finished with value: 35.09695953770627 and parameters: {'max_depth': 7, 'learning_rate': 0.02271528425841824, 'gamma': 0.8004064004005578, 'min_child_weight': 4, 'subsample': 0.6934941851224955, 'colsample_bytree': 0.7408035674648659}. Best is trial 21 with value: 34.40783537527264.

🏃 View run thoughtful-worm-554 at: http://localhost:5000/#/experiments/788856940458785600/runs/95e3c104388445a7bf308f80b1fe2be1
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:17:40,868] Trial 47 finished with value: 34.92338190097338 and parameters: {'max_depth': 8, 'learning_rate': 0.08401450791582608, 'gamma': 4.981357119143487, 'min_child_weight': 3, 'subsample': 0.8267397011401527, 'colsample_bytree': 0.965126724066074}. Best is trial 21 with value: 34.40783537527264.

🏃 View run classy-shrew-568 at: http://localhost:5000/#/experiments/788856940458785600/runs/b427c56142c34c259d26ffaf4aece936
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:17:46,698] Trial 48 finished with value: 34.75276407145414 and parameters: {'max_depth': 8, 'learning_rate': 0.05852711857782946, 'gamma': 3.598580493675275, 'min_child_weight': 6, 'subsample': 0.7851612800120322, 'colsample_bytree': 0.9294970638251828}. Best is trial 21 with value: 34.40783537527264.

🏃 View run languid-carp-756 at: http://localhost:5000/#/experiments/788856940458785600/runs/22c440728eca40138cc82dd0ea7c8e4b
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600

[I 2025-02-20 17:17:48,052] Trial 49 finished with value: 38.06276292945036 and parameters: {'max_depth': 10, 'learning_rate': 0.2636507014431756, 'gamma': 3.9976942093289645, 'min_child_weight': 9, 'subsample': 0.5933007097658699, 'colsample_bytree': 0.9971035028200741}. Best is trial 21 with value: 34.40783537527264.

🏃 View run casual-bass-858 at: http://localhost:5000/#/experiments/788856940458785600/runs/e1de099bef1443788b1e1d4b72196cf4
🧪 View experiment at: http://localhost:5000/#/experiments/788856940458785600
Melhor resultado:
FrozenTrial(number=21, state=TrialState.COMPLETE, values=[34.40783537527264], datetime_start=datetime.datetime(2025, 2, 20, 17, 14, 24, 902089), datetime_complete=datetime.datetime(2025, 2, 20, 17, 14, 32, 232698), params={'max_depth': 9, 'learning_rate': 0.04032633610146599, 'gamma': 3.103460583323776, 'min_child_weight': 9, 'subsample': 0.732925837962594, 'colsample_bytree': 0.8765889068068179}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'max_depth': IntDistribution(high=10, log=False, low=3, step=1), 'learning_rate': FloatDistribution(high=0.3, log=False, low=0.01, step=None), 'gamma': FloatDistribution(high=5.0, log=False, low=0.0, step=None), 'min_child_weight': IntDistribution(high=10, log=False, low=1, step=1), 'subsample': FloatDistribution(high=1.0, log=False, low=0.5, step=None), 'colsample_bytree': FloatDistribution(high=1.0, log=False, low=0.5, step=None)}, trial_id=21, value=None)

In [12]:
# Exibe os 10 melhores resultados
study_dmatrix.trials_dataframe().sort_values(by="value", ascending=True).head(10)

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_gamma,params_learning_rate,params_max_depth,params_min_child_weight,params_subsample,state
36,36,34.279833,2025-02-20 17:01:28.647891,2025-02-20 17:01:41.466488,0 days 00:00:12.818597,0.862370,4.962442,0.020595,10,9,0.710493,COMPLETE
33,33,34.352235,2025-02-20 17:01:00.300384,2025-02-20 17:01:13.052017,0 days 00:00:12.751633,0.843314,4.959555,0.018792,10,9,0.576328,COMPLETE
37,37,34.356974,2025-02-20 17:01:41.466488,2025-02-20 17:01:55.601557,0 days 00:00:14.135069,0.924169,4.378917,0.017317,10,9,0.712684,COMPLETE
38,38,34.374015,2025-02-20 17:01:55.601557,2025-02-20 17:02:10.848340,0 days 00:00:15.246783,0.915304,4.397476,0.014964,10,10,0.705173,COMPLETE
35,35,34.385417,2025-02-20 17:01:17.667115,2025-02-20 17:01:28.647891,0 days 00:00:10.980776,0.915892,4.380986,0.024204,10,9,0.699881,COMPLETE
42,42,34.388339,2025-02-20 17:02:46.380636,2025-02-20 17:02:58.334803,0 days 00:00:11.954167,0.869016,4.964180,0.021445,10,10,0.774608,COMPLETE
39,39,34.402127,2025-02-20 17:02:10.848340,2025-02-20 17:02:24.448344,0 days 00:00:13.600004,0.984465,4.283346,0.015669,9,10,0.727173,COMPLETE
32,32,34.443896,2025-02-20 17:00:51.613147,2025-02-20 17:01:00.300384,0 days 00:00:08.687237,0.849069,4.929645,0.029467,10,8,0.615685,COMPLETE
47,47,34.466450,2025-02-20 17:03:11.618053,2025-02-20 17:03:25.569713,0 days 00:00:13.951660,0.963294,4.344984,0.021490,10,9,0.851884,COMPLETE
43,43,34.534531,2025-02-20 17:02:58.334803,2025-02-20 17:03:04.648252,0 days 00:00:06.313449,0.927927,4.422444,0.048903,9,9,0.709702,COMPLETE

In [13]:
study_dmatrix.best_params

{'max_depth': 10,
 'learning_rate': 0.02059515711564996,
 'gamma': 4.96244196764165,
 'min_child_weight': 9,
 'subsample': 0.7104927008270152,
 'colsample_bytree': 0.8623696933619331}