# Importando as bibliotecas

In [ ]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import mlflow
import optuna

import warnings
warnings.filterwarnings("ignore")

# Carregando a base de dados

In [ ]:
data = pd.read_csv('data/bike.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  cnt         17379 non-null  int64
dtypes: float64(4), int64(10), object(1)
memory usage: 2.0+ MB

In [3]:
data.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
3,4,1/1/2011,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
4,5,1/1/2011,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

# Preparando o Dataset - Treino e Teste

In [4]:
# Converte a coluna 'dteday' para o tipo datetime
data['dteday'] = pd.to_datetime(data['dteday'])

In [5]:
# Divisão 80% treino e 20% teste
train = data.loc[data['dteday']< '2012-08-10']
test = data.loc[data['dteday']>= '2012-08-10']

In [6]:
# Porcentagem dos dados de treino
round(train.shape[0] / data.shape[0], 2)

0.8

In [7]:
train.drop(['instant', 'dteday'], axis=1, inplace=True)
test.drop(['instant', 'dteday'], axis=1, inplace=True)

# Validação Cruzada p/ teste de Modelos

In [8]:
# Separando as features e o target de treino
features_train = train.drop('cnt', axis=1)
target_train = train['cnt']

# Separando as features e o target de teste
features_test = test.drop('cnt', axis=1)
target_test = test['cnt']

In [24]:
def cross_validate_rmse(model, X, y, cv=5):
    scores = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv)
    rmse_scores = -scores
    mean_rmse = rmse_scores.mean()
    std_rmse = rmse_scores.std()
    return rmse_scores, mean_rmse, std_rmse

# Decision Tree
rmse_scores, mean_rmse, std_rmse = cross_validate_rmse(DecisionTreeRegressor(random_state=42), features_train, target_train)
print(f'Decision Tree: RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

# Random Forest
rmse_scores, mean_rmse, std_rmse = cross_validate_rmse(RandomForestRegressor(n_estimators=1000, random_state=42, n_jobs=-1), features_train, target_train)
print(f'Random Forest: RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

# XGBoost with DataFrame
rmse_scores, mean_rmse, std_rmse = cross_validate_rmse(xgb.XGBRegressor(objective='reg:squarederror', eval_metric='rmse', seed=42), features_train, target_train)
print(f'XGBoost (DataFrame): RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

# XGBoost with Dmatrix
dtrain = xgb.DMatrix(features_train, label=target_train)
params = {
    'objective': 'reg:squarederror',
    'eval_metric': 'rmse',
    'seed': 42
}
cv_results = xgb.cv(params, dtrain, num_boost_round=1000, nfold=5, early_stopping_rounds=10)
mean_rmse = cv_results['test-rmse-mean'].min()
std_rmse = cv_results['test-rmse-std'].min()
print(f'XGBoost (DMatrix): RMSE médio: {mean_rmse:.2f}, Desvio padrão: {std_rmse:.2f}')

Decision Tree: RMSE médio: 90.62, Desvio padrão: 15.20
Random Forest: RMSE médio: 71.25, Desvio padrão: 14.70
XGBoost (DataFrame): RMSE médio: 62.06, Desvio padrão: 7.56
XGBoost (DMatrix): RMSE médio: 36.87, Desvio padrão: 1.39

# Experiment Tracking com MLflow e XGBoost

In [ ]:
# Instancia o MLflow
mlflow.set_experiment("bike_rental")
mlflow.set_tracking_uri("http://localhost:5000")

2025/02/19 21:37:03 INFO mlflow.tracking.fluent: Experiment with name 'bike_rental' does not exist. Creating a new experiment.

In [27]:
# Otimização de hiperparâmetros com Optuna e registro no MLflow

def objective(trial):
    # Define os hiperparâmetros a serem otimizados
    param = {
        'objective': 'reg:squarederror',
        'eval_metric': 'rmse',
        'seed': 42,
        'max_depth': trial.suggest_int("max_depth", 3, 10),
        'learning_rate': trial.suggest_float("learning_rate", 0.01, 0.3),
        'gamma': trial.suggest_float("gamma", 0.0, 5.0),
        'min_child_weight': trial.suggest_int("min_child_weight", 1, 10),
        'subsample': trial.suggest_float("subsample", 0.5, 1.0),
        'colsample_bytree': trial.suggest_float("colsample_bytree", 0.5, 1.0)
    }
    
    # Inicia um run MLflow aninhado para registrar a trial corrente
    with mlflow.start_run(nested=True):
        mlflow.log_params(param)
        
        # Executa a validação cruzada com xgb.cv usando dtrain (definido em célula anterior)
        cv_results = xgb.cv(
            params=param,
            dtrain=dtrain,
            num_boost_round=1000,
            nfold=5,
            early_stopping_rounds=10,
            verbose_eval=False
        )
        
        # Retorna o menor RMSE obtido na validação cruzada
        best_rmse = cv_results['test-rmse-mean'].min()
        mlflow.log_metric("best_rmse", best_rmse)
    
    return best_rmse

# Cria um estudo Optuna e otimiza a função objetivo
study_dmatrix = optuna.create_study(direction="minimize")
study_dmatrix.optimize(objective, n_trials=50)

print("Melhor resultado:")
print(study_dmatrix.best_trial)

[I 2025-02-19 22:14:46,254] A new study created in memory with name: no-name-a5e86e06-9ef5-45d8-8268-661bf0586388
[I 2025-02-19 22:14:54,942] Trial 0 finished with value: 43.234122876565266 and parameters: {'max_depth': 3, 'learning_rate': 0.17927639741854914, 'gamma': 4.44202582950418, 'min_child_weight': 10, 'subsample': 0.5092200494944793, 'colsample_bytree': 0.9346162116685763}. Best is trial 0 with value: 43.234122876565266.

🏃 View run chill-cow-880 at: http://localhost:5000/#/experiments/626468295712000692/runs/7d08b51792034bb7a7e8da92cc9994fd
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:14:57,792] Trial 1 finished with value: 35.92841371107319 and parameters: {'max_depth': 10, 'learning_rate': 0.12951246155361593, 'gamma': 1.8402041944751861, 'min_child_weight': 1, 'subsample': 0.6093854409236971, 'colsample_bytree': 0.8547916840526999}. Best is trial 1 with value: 35.92841371107319.

🏃 View run spiffy-ram-555 at: http://localhost:5000/#/experiments/626468295712000692/runs/6a3ce8ca92fc4740bdd19fa60e32f0c8
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:14:59,459] Trial 2 finished with value: 36.35340254880178 and parameters: {'max_depth': 10, 'learning_rate': 0.1914364178108559, 'gamma': 1.7943784685637048, 'min_child_weight': 9, 'subsample': 0.6609401307082885, 'colsample_bytree': 0.8701249211865612}. Best is trial 1 with value: 35.92841371107319.

🏃 View run bedecked-shad-311 at: http://localhost:5000/#/experiments/626468295712000692/runs/80af6107b84c46dc963a1774590d974e
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:06,299] Trial 3 finished with value: 34.82874950088865 and parameters: {'max_depth': 8, 'learning_rate': 0.03943673716968659, 'gamma': 0.3904687396765144, 'min_child_weight': 9, 'subsample': 0.8507060278641211, 'colsample_bytree': 0.7590228867963096}. Best is trial 3 with value: 34.82874950088865.

🏃 View run incongruous-pug-787 at: http://localhost:5000/#/experiments/626468295712000692/runs/7a58a8c5c53b4f21b551d1b20afc83d5
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:12,605] Trial 4 finished with value: 35.82530587992629 and parameters: {'max_depth': 5, 'learning_rate': 0.0991287077800927, 'gamma': 4.907524622329602, 'min_child_weight': 3, 'subsample': 0.7763048595967348, 'colsample_bytree': 0.8702533412593989}. Best is trial 3 with value: 34.82874950088865.

🏃 View run redolent-shrew-668 at: http://localhost:5000/#/experiments/626468295712000692/runs/54d11971209b4d489c89f7a9c1c5d52b
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:14,655] Trial 5 finished with value: 38.638142016711434 and parameters: {'max_depth': 9, 'learning_rate': 0.23248923946933533, 'gamma': 3.7929887521941, 'min_child_weight': 5, 'subsample': 0.6641937179676556, 'colsample_bytree': 0.6133957072010692}. Best is trial 3 with value: 34.82874950088865.

🏃 View run respected-duck-171 at: http://localhost:5000/#/experiments/626468295712000692/runs/8d666ab6ca9342da84cf3f6601382920
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:16,539] Trial 6 finished with value: 38.751866158125736 and parameters: {'max_depth': 9, 'learning_rate': 0.2908709057265297, 'gamma': 4.150863362666297, 'min_child_weight': 10, 'subsample': 0.8172787833607049, 'colsample_bytree': 0.7080160043151411}. Best is trial 3 with value: 34.82874950088865.

🏃 View run able-skink-735 at: http://localhost:5000/#/experiments/626468295712000692/runs/929cfb6a45ab4f358ced667e465e38dc
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:23,867] Trial 7 finished with value: 49.435797819086346 and parameters: {'max_depth': 3, 'learning_rate': 0.03577339554326286, 'gamma': 0.37414102080863987, 'min_child_weight': 9, 'subsample': 0.6952096119407117, 'colsample_bytree': 0.8105679256845235}. Best is trial 3 with value: 34.82874950088865.

🏃 View run casual-pug-137 at: http://localhost:5000/#/experiments/626468295712000692/runs/f2786d63d9e34c2b91cd6bab09ae6ad8
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:31,093] Trial 8 finished with value: 47.45830733244448 and parameters: {'max_depth': 3, 'learning_rate': 0.04783757993864885, 'gamma': 4.942729871119385, 'min_child_weight': 4, 'subsample': 0.8116692780500525, 'colsample_bytree': 0.9914342344829357}. Best is trial 3 with value: 34.82874950088865.

🏃 View run beautiful-mole-405 at: http://localhost:5000/#/experiments/626468295712000692/runs/faa484bde3ed42a1979ba8517254c8f1
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:36,375] Trial 9 finished with value: 37.835391352082965 and parameters: {'max_depth': 4, 'learning_rate': 0.1959905728997496, 'gamma': 3.7200469418314124, 'min_child_weight': 4, 'subsample': 0.8799412402510094, 'colsample_bytree': 0.9119920086426914}. Best is trial 3 with value: 34.82874950088865.

🏃 View run painted-stag-905 at: http://localhost:5000/#/experiments/626468295712000692/runs/ae03f761801a48e3a64aab103c68aaa7
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:41,326] Trial 10 finished with value: 35.69262179564962 and parameters: {'max_depth': 7, 'learning_rate': 0.09313363205165154, 'gamma': 0.026486355877264722, 'min_child_weight': 7, 'subsample': 0.9899698657596512, 'colsample_bytree': 0.6982102410785631}. Best is trial 3 with value: 34.82874950088865.

🏃 View run kindly-roo-949 at: http://localhost:5000/#/experiments/626468295712000692/runs/d1bac994b02e4647b384988b5acaf2af
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:45,892] Trial 11 finished with value: 35.62317604844227 and parameters: {'max_depth': 7, 'learning_rate': 0.08411089848219959, 'gamma': 0.162552534462541, 'min_child_weight': 7, 'subsample': 0.9877516127292891, 'colsample_bytree': 0.6934674303301894}. Best is trial 3 with value: 34.82874950088865.

🏃 View run angry-shoat-898 at: http://localhost:5000/#/experiments/626468295712000692/runs/d8ba6a1206df4c06bd7d782bbd9da4d5
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:15:57,619] Trial 12 finished with value: 37.80103725931455 and parameters: {'max_depth': 7, 'learning_rate': 0.01168249448684552, 'gamma': 0.9249816220827538, 'min_child_weight': 7, 'subsample': 0.9784281594594306, 'colsample_bytree': 0.5114211720837236}. Best is trial 3 with value: 34.82874950088865.

🏃 View run receptive-bird-344 at: http://localhost:5000/#/experiments/626468295712000692/runs/af34d6fac84b4de7af7adaa0a019dce9
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:06,777] Trial 13 finished with value: 35.43598286660695 and parameters: {'max_depth': 6, 'learning_rate': 0.07104693231291635, 'gamma': 1.0388261857678638, 'min_child_weight': 7, 'subsample': 0.9053222413150229, 'colsample_bytree': 0.6293622231294422}. Best is trial 3 with value: 34.82874950088865.

🏃 View run placid-eel-498 at: http://localhost:5000/#/experiments/626468295712000692/runs/cfe428ab5cf64d82904adb0613484065
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:17,025] Trial 14 finished with value: 35.50035683701442 and parameters: {'max_depth': 6, 'learning_rate': 0.05762095460911583, 'gamma': 1.2111728217616786, 'min_child_weight': 8, 'subsample': 0.8847880811178493, 'colsample_bytree': 0.6045549599875891}. Best is trial 3 with value: 34.82874950088865.

🏃 View run luminous-kite-830 at: http://localhost:5000/#/experiments/626468295712000692/runs/4233ee599ca74466994fdf48f4279f00
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:19,787] Trial 15 finished with value: 35.46827981683109 and parameters: {'max_depth': 8, 'learning_rate': 0.13439206692359829, 'gamma': 2.8053052019887743, 'min_child_weight': 6, 'subsample': 0.897535048906736, 'colsample_bytree': 0.7646730792032991}. Best is trial 3 with value: 34.82874950088865.

🏃 View run intelligent-stag-90 at: http://localhost:5000/#/experiments/626468295712000692/runs/8f044d4f1b8a4118a5872eeb9a392344
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:28,688] Trial 16 finished with value: 43.91013806203512 and parameters: {'max_depth': 5, 'learning_rate': 0.010622082401834224, 'gamma': 0.8559715075231316, 'min_child_weight': 8, 'subsample': 0.9199160405009758, 'colsample_bytree': 0.6200947401060072}. Best is trial 3 with value: 34.82874950088865.

🏃 View run colorful-wolf-716 at: http://localhost:5000/#/experiments/626468295712000692/runs/1f03f096510c4dd89079303857b55e59
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:36,173] Trial 17 finished with value: 35.68611751698575 and parameters: {'max_depth': 6, 'learning_rate': 0.07054677665624301, 'gamma': 2.4881632197005423, 'min_child_weight': 6, 'subsample': 0.8402599954365166, 'colsample_bytree': 0.5052206963819732}. Best is trial 3 with value: 34.82874950088865.

🏃 View run illustrious-gnat-143 at: http://localhost:5000/#/experiments/626468295712000692/runs/31142454b84249ddb4472a25ae3046f0
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:38,576] Trial 18 finished with value: 35.83859141081276 and parameters: {'max_depth': 8, 'learning_rate': 0.13241309356256115, 'gamma': 1.5173389322931117, 'min_child_weight': 8, 'subsample': 0.7269365466790203, 'colsample_bytree': 0.7723742555341039}. Best is trial 3 with value: 34.82874950088865.

🏃 View run enchanting-goose-631 at: http://localhost:5000/#/experiments/626468295712000692/runs/c87b096836a24692bca8878772a82705
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:42,031] Trial 19 finished with value: 36.08217768497522 and parameters: {'max_depth': 8, 'learning_rate': 0.10443336258017798, 'gamma': 2.4559181757224335, 'min_child_weight': 9, 'subsample': 0.9331644303590496, 'colsample_bytree': 0.5529050948213201}. Best is trial 3 with value: 34.82874950088865.

🏃 View run masked-ram-106 at: http://localhost:5000/#/experiments/626468295712000692/runs/840495fc8b4c42deb2031d09551250c0
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:50,764] Trial 20 finished with value: 37.1402898535707 and parameters: {'max_depth': 5, 'learning_rate': 0.034470416285397834, 'gamma': 0.45633563886187806, 'min_child_weight': 1, 'subsample': 0.7659523485509501, 'colsample_bytree': 0.679695648164993}. Best is trial 3 with value: 34.82874950088865.

🏃 View run carefree-auk-671 at: http://localhost:5000/#/experiments/626468295712000692/runs/e3ed2bdc6b27418c9238d310d3a365c7
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:53,634] Trial 21 finished with value: 36.334717189543895 and parameters: {'max_depth': 8, 'learning_rate': 0.15429025524211665, 'gamma': 3.043664853638127, 'min_child_weight': 6, 'subsample': 0.8713225459044849, 'colsample_bytree': 0.7480238760430742}. Best is trial 3 with value: 34.82874950088865.

🏃 View run legendary-auk-432 at: http://localhost:5000/#/experiments/626468295712000692/runs/ef0f63c234b840b39d115870e71bba6a
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:16:56,352] Trial 22 finished with value: 36.00437176858119 and parameters: {'max_depth': 9, 'learning_rate': 0.12719794393175896, 'gamma': 3.0365926700082504, 'min_child_weight': 5, 'subsample': 0.9328975730357576, 'colsample_bytree': 0.7815526698742519}. Best is trial 3 with value: 34.82874950088865.

🏃 View run welcoming-flea-426 at: http://localhost:5000/#/experiments/626468295712000692/runs/c0c6ca9b918a4b46805052addb6a2001
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:17:02,423] Trial 23 finished with value: 35.270367664269784 and parameters: {'max_depth': 8, 'learning_rate': 0.06828592439473177, 'gamma': 2.0640600685928687, 'min_child_weight': 6, 'subsample': 0.8464539474301216, 'colsample_bytree': 0.6543124262118666}. Best is trial 3 with value: 34.82874950088865.

🏃 View run bemused-penguin-836 at: http://localhost:5000/#/experiments/626468295712000692/runs/dcbd83d1754f43ca8772f189ec6d44e9
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:17:10,225] Trial 24 finished with value: 35.56443606025421 and parameters: {'max_depth': 6, 'learning_rate': 0.06964049008919752, 'gamma': 2.041977489280245, 'min_child_weight': 7, 'subsample': 0.8357179460623367, 'colsample_bytree': 0.6553628957193868}. Best is trial 3 with value: 34.82874950088865.

🏃 View run debonair-ox-50 at: http://localhost:5000/#/experiments/626468295712000692/runs/81deba4d92d745edbfc789a7884e0532
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:17:18,127] Trial 25 finished with value: 35.39019013718502 and parameters: {'max_depth': 7, 'learning_rate': 0.050635340802786054, 'gamma': 0.7617541886971491, 'min_child_weight': 8, 'subsample': 0.781568001961019, 'colsample_bytree': 0.5565236049650912}. Best is trial 3 with value: 34.82874950088865.

🏃 View run trusting-chimp-227 at: http://localhost:5000/#/experiments/626468295712000692/runs/605d487744014a96a34e02eb6f17aace
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:17:29,271] Trial 26 finished with value: 35.34801177895055 and parameters: {'max_depth': 7, 'learning_rate': 0.03063694839951385, 'gamma': 0.6138156082483976, 'min_child_weight': 9, 'subsample': 0.732825028752801, 'colsample_bytree': 0.5639959732674624}. Best is trial 3 with value: 34.82874950088865.

🏃 View run valuable-ant-739 at: http://localhost:5000/#/experiments/626468295712000692/runs/936cd98ade3d4244b91f2e8d16ab015c
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:17:40,913] Trial 27 finished with value: 35.05817940607862 and parameters: {'max_depth': 9, 'learning_rate': 0.027922971473843032, 'gamma': 1.4543475839848676, 'min_child_weight': 10, 'subsample': 0.5941785604475647, 'colsample_bytree': 0.5835189257106317}. Best is trial 3 with value: 34.82874950088865.

🏃 View run beautiful-asp-299 at: http://localhost:5000/#/experiments/626468295712000692/runs/c6d1818017da4448b99172ec034b87e6
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:17:52,965] Trial 28 finished with value: 34.806594219813306 and parameters: {'max_depth': 9, 'learning_rate': 0.02242042135605006, 'gamma': 1.399647598622055, 'min_child_weight': 10, 'subsample': 0.5342999267266272, 'colsample_bytree': 0.7376714590865973}. Best is trial 28 with value: 34.806594219813306.

🏃 View run gaudy-grub-227 at: http://localhost:5000/#/experiments/626468295712000692/runs/fc5feb8ac97b41e0a5a43c56202da0c1
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:18:05,243] Trial 29 finished with value: 34.863649495932876 and parameters: {'max_depth': 9, 'learning_rate': 0.0207536771052413, 'gamma': 1.3826156572991894, 'min_child_weight': 10, 'subsample': 0.5286891998780197, 'colsample_bytree': 0.7334044671178307}. Best is trial 28 with value: 34.806594219813306.

🏃 View run popular-midge-695 at: http://localhost:5000/#/experiments/626468295712000692/runs/a84a05a6921f40f69e7c5c8c49ece8b1
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:18:21,327] Trial 30 finished with value: 34.74510804694118 and parameters: {'max_depth': 10, 'learning_rate': 0.011411114106687853, 'gamma': 1.3450175545644472, 'min_child_weight': 10, 'subsample': 0.5164058356741102, 'colsample_bytree': 0.8125982057212653}. Best is trial 30 with value: 34.74510804694118.

🏃 View run calm-slug-826 at: http://localhost:5000/#/experiments/626468295712000692/runs/9a49e4c1e8f44dda94d588ea6794b5bf
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:18:37,357] Trial 31 finished with value: 34.61688779770681 and parameters: {'max_depth': 10, 'learning_rate': 0.012944217648835245, 'gamma': 1.3296882075737397, 'min_child_weight': 10, 'subsample': 0.5139946743119133, 'colsample_bytree': 0.8248725395405869}. Best is trial 31 with value: 34.61688779770681.

🏃 View run bouncy-squirrel-538 at: http://localhost:5000/#/experiments/626468295712000692/runs/d6b76f439853465686300609bf7f29f0
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:18:43,503] Trial 32 finished with value: 35.04810306590668 and parameters: {'max_depth': 10, 'learning_rate': 0.044171586784541556, 'gamma': 1.7109711711951472, 'min_child_weight': 10, 'subsample': 0.5230032951698251, 'colsample_bytree': 0.8109081069976639}. Best is trial 31 with value: 34.61688779770681.

🏃 View run silent-mink-889 at: http://localhost:5000/#/experiments/626468295712000692/runs/84a4f90c2b03472dbb0ecdbeeac3fcd1
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:00,254] Trial 33 finished with value: 34.65870189020693 and parameters: {'max_depth': 10, 'learning_rate': 0.010637747449029102, 'gamma': 0.3351186041389024, 'min_child_weight': 9, 'subsample': 0.5562527014461999, 'colsample_bytree': 0.8160120882452128}. Best is trial 31 with value: 34.61688779770681.

🏃 View run upset-mare-814 at: http://localhost:5000/#/experiments/626468295712000692/runs/e684f88a713249a69db35187d1543538
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:16,579] Trial 34 finished with value: 34.4139603911194 and parameters: {'max_depth': 10, 'learning_rate': 0.013347183182815954, 'gamma': 2.1163012424840013, 'min_child_weight': 10, 'subsample': 0.5654399968374698, 'colsample_bytree': 0.8372619383515302}. Best is trial 34 with value: 34.4139603911194.

🏃 View run melodic-finch-51 at: http://localhost:5000/#/experiments/626468295712000692/runs/ab2f51a0b8484f11b0d39b6e69e8cfd8
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:33,178] Trial 35 finished with value: 34.34207656467384 and parameters: {'max_depth': 10, 'learning_rate': 0.0140717901612381, 'gamma': 2.18115950523157, 'min_child_weight': 9, 'subsample': 0.568153688660201, 'colsample_bytree': 0.838446676388734}. Best is trial 35 with value: 34.34207656467384.

🏃 View run auspicious-mare-236 at: http://localhost:5000/#/experiments/626468295712000692/runs/86c2476e1ef2489ba3b86a26f47ceda5
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:34,396] Trial 36 finished with value: 37.80864135083264 and parameters: {'max_depth': 10, 'learning_rate': 0.24859937976509167, 'gamma': 2.3086696413614267, 'min_child_weight': 9, 'subsample': 0.5807197691163697, 'colsample_bytree': 0.8543192546141303}. Best is trial 35 with value: 34.34207656467384.

🏃 View run fun-skink-365 at: http://localhost:5000/#/experiments/626468295712000692/runs/e3567016d74d4195a4a822ecd6bcd958
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:39,357] Trial 37 finished with value: 34.93205457806859 and parameters: {'max_depth': 10, 'learning_rate': 0.05351412860145848, 'gamma': 1.9891553231600454, 'min_child_weight': 9, 'subsample': 0.5619999906447193, 'colsample_bytree': 0.915581764898578}. Best is trial 35 with value: 34.34207656467384.

🏃 View run exultant-koi-952 at: http://localhost:5000/#/experiments/626468295712000692/runs/47ba928c381c46329e68c8e892a78a5c
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:42,462] Trial 38 finished with value: 35.519115149867666 and parameters: {'max_depth': 10, 'learning_rate': 0.10921003259447677, 'gamma': 2.7500100816963053, 'min_child_weight': 8, 'subsample': 0.6309190634570915, 'colsample_bytree': 0.8441326061743549}. Best is trial 35 with value: 34.34207656467384.

🏃 View run funny-roo-224 at: http://localhost:5000/#/experiments/626468295712000692/runs/2fac8fbf8bda4e88b7ea1fd008b28228
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:43,727] Trial 39 finished with value: 38.55122167480211 and parameters: {'max_depth': 10, 'learning_rate': 0.29813864792186634, 'gamma': 1.7288591647653746, 'min_child_weight': 9, 'subsample': 0.6523335497734857, 'colsample_bytree': 0.8834544669016315}. Best is trial 35 with value: 34.34207656467384.

🏃 View run debonair-bee-563 at: http://localhost:5000/#/experiments/626468295712000692/runs/bdcdcae7ba0344a88fa38737c94cbd62
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:50,844] Trial 40 finished with value: 34.55805772620873 and parameters: {'max_depth': 9, 'learning_rate': 0.03698125275696837, 'gamma': 2.2915259846902187, 'min_child_weight': 10, 'subsample': 0.5565830525832861, 'colsample_bytree': 0.9600898188982446}. Best is trial 35 with value: 34.34207656467384.

🏃 View run upbeat-grouse-936 at: http://localhost:5000/#/experiments/626468295712000692/runs/12157deeb86d4fb594c002de8191e6bf
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:19:59,234] Trial 41 finished with value: 34.52538099363202 and parameters: {'max_depth': 10, 'learning_rate': 0.0356739954203234, 'gamma': 3.3784130628516325, 'min_child_weight': 10, 'subsample': 0.5601991223025298, 'colsample_bytree': 0.9764798885394891}. Best is trial 35 with value: 34.34207656467384.

🏃 View run adaptable-doe-792 at: http://localhost:5000/#/experiments/626468295712000692/runs/2b8d003d7d094b11bd752fa9c6c71a0d
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:06,171] Trial 42 finished with value: 34.61382375656625 and parameters: {'max_depth': 9, 'learning_rate': 0.03799343433924873, 'gamma': 3.4608959722707726, 'min_child_weight': 10, 'subsample': 0.6055202412075177, 'colsample_bytree': 0.9802672558781349}. Best is trial 35 with value: 34.34207656467384.

🏃 View run fun-bug-178 at: http://localhost:5000/#/experiments/626468295712000692/runs/cf2c9635b7634bd8b6d5328be950426c
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:13,686] Trial 43 finished with value: 34.53982260467182 and parameters: {'max_depth': 9, 'learning_rate': 0.03802873001120095, 'gamma': 3.654206701818573, 'min_child_weight': 10, 'subsample': 0.6181259215627646, 'colsample_bytree': 0.9885238256853539}. Best is trial 35 with value: 34.34207656467384.

🏃 View run intelligent-lamb-357 at: http://localhost:5000/#/experiments/626468295712000692/runs/878eaa5ce57041f7bd2596dcd67d58a1
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:17,383] Trial 44 finished with value: 34.92743891789094 and parameters: {'max_depth': 9, 'learning_rate': 0.08064485994945092, 'gamma': 4.485666866119754, 'min_child_weight': 10, 'subsample': 0.6218594029160052, 'colsample_bytree': 0.9606056682525501}. Best is trial 35 with value: 34.34207656467384.

🏃 View run efficient-vole-224 at: http://localhost:5000/#/experiments/626468295712000692/runs/ee1ced1c3e7a40a498b8a5328e87b876
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:22,219] Trial 45 finished with value: 34.64363747204081 and parameters: {'max_depth': 9, 'learning_rate': 0.05116148353551522, 'gamma': 3.486644354194044, 'min_child_weight': 2, 'subsample': 0.558861532839716, 'colsample_bytree': 0.9491356744875112}. Best is trial 35 with value: 34.34207656467384.

🏃 View run victorious-shrimp-61 at: http://localhost:5000/#/experiments/626468295712000692/runs/93806a6baa844697a13092e872c87c98
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:24,116] Trial 46 finished with value: 36.336050330163225 and parameters: {'max_depth': 10, 'learning_rate': 0.17798849725425808, 'gamma': 4.114769872243909, 'min_child_weight': 10, 'subsample': 0.6815149357032123, 'colsample_bytree': 0.9994968201895198}. Best is trial 35 with value: 34.34207656467384.

🏃 View run burly-hare-978 at: http://localhost:5000/#/experiments/626468295712000692/runs/0a07c2d82f6144c0a233975b557d11a0
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:28,954] Trial 47 finished with value: 34.84609642541673 and parameters: {'max_depth': 10, 'learning_rate': 0.05941317678494556, 'gamma': 3.21101425198396, 'min_child_weight': 9, 'subsample': 0.5876924404431245, 'colsample_bytree': 0.9016350864348961}. Best is trial 35 with value: 34.34207656467384.

🏃 View run charming-stoat-854 at: http://localhost:5000/#/experiments/626468295712000692/runs/585bd7e127044808a40123af4cba571a
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:35,702] Trial 48 finished with value: 34.52624376393399 and parameters: {'max_depth': 9, 'learning_rate': 0.03981888185315734, 'gamma': 2.722685711732997, 'min_child_weight': 10, 'subsample': 0.6406041478967199, 'colsample_bytree': 0.9412702412739683}. Best is trial 35 with value: 34.34207656467384.

🏃 View run angry-seal-75 at: http://localhost:5000/#/experiments/626468295712000692/runs/441e151b954d4281b07c179768dfd4c3
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692

[I 2025-02-19 22:20:39,045] Trial 49 finished with value: 35.08777231989015 and parameters: {'max_depth': 8, 'learning_rate': 0.09495771770587279, 'gamma': 2.774534188635514, 'min_child_weight': 8, 'subsample': 0.6374899455834234, 'colsample_bytree': 0.9354613993146264}. Best is trial 35 with value: 34.34207656467384.

🏃 View run carefree-mare-791 at: http://localhost:5000/#/experiments/626468295712000692/runs/59e5593a6ce3492b90398538deec156a
🧪 View experiment at: http://localhost:5000/#/experiments/626468295712000692
Melhor resultado:
FrozenTrial(number=35, state=TrialState.COMPLETE, values=[34.34207656467384], datetime_start=datetime.datetime(2025, 2, 19, 22, 19, 16, 580193), datetime_complete=datetime.datetime(2025, 2, 19, 22, 19, 33, 178906), params={'max_depth': 10, 'learning_rate': 0.0140717901612381, 'gamma': 2.18115950523157, 'min_child_weight': 9, 'subsample': 0.568153688660201, 'colsample_bytree': 0.838446676388734}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'max_depth': IntDistribution(high=10, log=False, low=3, step=1), 'learning_rate': FloatDistribution(high=0.3, log=False, low=0.01, step=None), 'gamma': FloatDistribution(high=5.0, log=False, low=0.0, step=None), 'min_child_weight': IntDistribution(high=10, log=False, low=1, step=1), 'subsample': FloatDistribution(high=1.0, log=False, low=0.5, step=None), 'colsample_bytree': FloatDistribution(high=1.0, log=False, low=0.5, step=None)}, trial_id=35, value=None)

In [ ]:
# Exibe os 10 melhores resultados
study_dmatrix.trials_dataframe().sort_values(by="value", ascending=True).head(10)

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_gamma,params_learning_rate,params_max_depth,params_min_child_weight,params_subsample,state
35,35,34.342077,2025-02-19 22:19:16.580193,2025-02-19 22:19:33.178906,0 days 00:00:16.598713,0.838447,2.181160,0.014072,10,9,0.568154,COMPLETE
34,34,34.413960,2025-02-19 22:19:00.254591,2025-02-19 22:19:16.579193,0 days 00:00:16.324602,0.837262,2.116301,0.013347,10,10,0.565440,COMPLETE
41,41,34.525381,2025-02-19 22:19:50.845453,2025-02-19 22:19:59.234331,0 days 00:00:08.388878,0.976480,3.378413,0.035674,10,10,0.560199,COMPLETE
48,48,34.526244,2025-02-19 22:20:28.954692,2025-02-19 22:20:35.701833,0 days 00:00:06.747141,0.941270,2.722686,0.039819,9,10,0.640604,COMPLETE
43,43,34.539823,2025-02-19 22:20:06.172980,2025-02-19 22:20:13.685824,0 days 00:00:07.512844,0.988524,3.654207,0.038029,9,10,0.618126,COMPLETE
40,40,34.558058,2025-02-19 22:19:43.727971,2025-02-19 22:19:50.844450,0 days 00:00:07.116479,0.960090,2.291526,0.036981,9,10,0.556583,COMPLETE
42,42,34.613824,2025-02-19 22:19:59.236330,2025-02-19 22:20:06.171981,0 days 00:00:06.935651,0.980267,3.460896,0.037993,9,10,0.605520,COMPLETE
31,31,34.616888,2025-02-19 22:18:21.328801,2025-02-19 22:18:37.357661,0 days 00:00:16.028860,0.824873,1.329688,0.012944,10,10,0.513995,COMPLETE
45,45,34.643637,2025-02-19 22:20:17.384811,2025-02-19 22:20:22.218916,0 days 00:00:04.834105,0.949136,3.486644,0.051161,9,2,0.558862,COMPLETE
33,33,34.658702,2025-02-19 22:18:43.504098,2025-02-19 22:19:00.253589,0 days 00:00:16.749491,0.816012,0.335119,0.010638,10,9,0.556253,COMPLETE

In [ ]:
study_dmatrix.best_params